### ISSUE TITLE
Reuse board for Gary replacement

### ISSUE THREAD

**Issue by niklasekstrom** [LIV2/Bluster#5]
By routing pins 25, 43, and 44 on the 48-pin DIP socket to free pins on the CPLD, it is possible to reuse the PCB to replace the Gary chip in an A500, using a different RTL.

**Comment by LIV2** [comment]
I forgot about this. I will do this soon :)

**Comment by LIV2** [comment]
@niklasekstrom I have routed these extra pins now in the rev_c branch. I will merge to master after testing the new board

**Comment by LIV2** [comment]
Merged Rev C a while ago :)
